
package interfacegrafica;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

public class CadastroJFrame extends javax.swing.JFrame {

    private VisualizarJFrame telaVisualizar;
    /**
     * Creates new form CadastroJFrame
     */
    public CadastroJFrame(VisualizarJFrame telaVisualizar) {
        initComponents();
        this.telaVisualizar = telaVisualizar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        txtFieldNome = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtFieldCPF = new javax.swing.JFormattedTextField();
        lblTelefone1 = new javax.swing.JLabel();
        lblRG = new javax.swing.JLabel();
        lblTelefone2 = new javax.swing.JLabel();
        lblFantasia = new javax.swing.JLabel();
        lblCNPJ = new javax.swing.JLabel();
        lblEstadual = new javax.swing.JLabel();
        jRadioButtonFisica = new javax.swing.JRadioButton();
        jRadioButtonJuridica = new javax.swing.JRadioButton();
        lblEndereco = new javax.swing.JLabel();
        txtFieldTelefone1 = new javax.swing.JFormattedTextField();
        txtFieldTelefone2 = new javax.swing.JFormattedTextField();
        txtFieldrg = new javax.swing.JFormattedTextField();
        lblEmail = new javax.swing.JLabel();
        txtFieldEstadual = new javax.swing.JTextField();
        txtFieldFantasia = new javax.swing.JTextField();
        lblTelefone3 = new javax.swing.JLabel();
        txtFieldTelefone3 = new javax.swing.JFormattedTextField();
        lblEmail1 = new javax.swing.JLabel();
        txtFieldEmail1 = new javax.swing.JTextField();
        lblEndereco1 = new javax.swing.JLabel();
        txtFieldEndereco1 = new javax.swing.JTextField();
        txtFieldEndereco = new javax.swing.JTextField();
        txtFieldEmail = new javax.swing.JTextField();
        txtFieldcnpj = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome:");

        lblCPF.setText("CPF:");

        txtFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNomeActionPerformed(evt);
            }
        });

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Botoes_Site_5752_Knob_Add.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setEnabled(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/edit-clear.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Botoes_Site_5752_Knob_Left.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        try {
            txtFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldCPFActionPerformed(evt);
            }
        });

        lblTelefone1.setText("Telefone:");

        lblRG.setText("RG:");

        lblTelefone2.setText("Celular:");

        lblFantasia.setText("Nome Fantasia:");

        lblCNPJ.setText("CNPJ:");

        lblEstadual.setText("Inscrição Estadual:");

        buttonGroup1.add(jRadioButtonFisica);
        jRadioButtonFisica.setText("Pessoa Física");
        jRadioButtonFisica.setToolTipText("");
        jRadioButtonFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFisicaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonJuridica);
        jRadioButtonJuridica.setText("Pessoa Jurídica");
        jRadioButtonJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJuridicaActionPerformed(evt);
            }
        });

        lblEndereco.setText("Endereço:");

        try {
            txtFieldTelefone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFieldTelefone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldTelefone1ActionPerformed(evt);
            }
        });

        try {
            txtFieldTelefone2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFieldTelefone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldTelefone2ActionPerformed(evt);
            }
        });

        try {
            txtFieldrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFieldrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldrgActionPerformed(evt);
            }
        });

        lblEmail.setText("Email:");

        txtFieldFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldFantasiaActionPerformed(evt);
            }
        });

        lblTelefone3.setText("Telefone:");

        try {
            txtFieldTelefone3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFieldTelefone3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldTelefone3ActionPerformed(evt);
            }
        });

        lblEmail1.setText("Email:");

        txtFieldEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldEmail1ActionPerformed(evt);
            }
        });

        lblEndereco1.setText("Endereço:");

        txtFieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldEnderecoActionPerformed(evt);
            }
        });

        txtFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldEmailActionPerformed(evt);
            }
        });

        try {
            txtFieldcnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFieldcnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldcnpjActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel.setText("Cadastro de Pessoas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblCPF)
                                    .addComponent(lblRG))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldrg, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFantasia)
                                    .addComponent(lblCNPJ))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jRadioButtonFisica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonJuridica))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFieldFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtFieldEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtFieldcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTelefone1)
                                .addGap(29, 29, 29)
                                .addComponent(txtFieldTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEstadual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCadastrar)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTelefone2)
                                            .addComponent(lblEndereco)
                                            .addComponent(lblEmail))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFieldTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLimpar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnVoltar)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblEmail1)
                                                    .addComponent(lblEndereco1)
                                                    .addComponent(lblTelefone3))
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtFieldTelefone3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtFieldEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addComponent(jLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndereco)
                    .addComponent(txtFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCPF)
                        .addComponent(txtFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelefone2)
                        .addComponent(txtFieldTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(txtFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRG)
                    .addComponent(txtFieldrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonFisica)
                    .addComponent(jRadioButtonJuridica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFantasia)
                    .addComponent(txtFieldFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone3)
                    .addComponent(txtFieldTelefone3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCNPJ)
                    .addComponent(txtFieldcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndereco1)
                    .addComponent(txtFieldEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadual)
                    .addComponent(txtFieldEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadastrar)
                        .addComponent(btnVoltar))
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void limparCampos(){
        txtFieldCPF.setText("");
        txtFieldNome.setText("");
        txtFieldrg.setText("");
        txtFieldTelefone1.setText("");
        txtFieldTelefone2.setText("");
        txtFieldEmail.setText("");
        txtFieldEmail1.setText("");
        txtFieldFantasia.setText("");
        txtFieldcnpj.setText("");
        txtFieldTelefone3.setText("");
        txtFieldEndereco.setText("");
        txtFieldEndereco1.setText("");
        
    }
    
    public void mostrarPessoa(Pessoa p){
        
        if (p instanceof PessoaFisica){
            PessoaFisica f = (PessoaFisica)p;
            txtFieldNome.setText(f.getNome());
            txtFieldCPF.setText(f.getCpf());
            txtFieldrg.setText(f.getRg());
            txtFieldTelefone1.setText(f.getTelefone());
            txtFieldEndereco.setText(f.getEndereco());
            txtFieldTelefone2.setText(f.getCelular());
            txtFieldEmail.setText(f.getEmail());
            
         
        }else if (p instanceof PessoaJuridica){
            PessoaJuridica j = (PessoaJuridica)p;
            txtFieldFantasia.setText(j.getNome());
            txtFieldEndereco1.setText(j.getEndereco());
            txtFieldEstadual.setText(j.getInscricaoestadual());
            txtFieldTelefone3.setText(j.getTelefone());
            txtFieldcnpj.setText(j.getCnpj());
            txtFieldEndereco1.setText(j.getEndereco());
            txtFieldEmail1.setText(j.getEmail());
        }
        desabilitarCampos();
        this.setVisible(true);    
    }
    
    public void EditarPessoa(Pessoa p){
        
        if (p instanceof PessoaFisica){
            PessoaFisica f = (PessoaFisica)p;
            txtFieldNome.setText(f.getNome());
            txtFieldCPF.setText(f.getCpf());
            txtFieldrg.setText(f.getRg());
            txtFieldTelefone1.setText(f.getTelefone());
            txtFieldEndereco.setText(f.getEndereco());
            txtFieldTelefone2.setText(f.getCelular());
            txtFieldEmail.setText(f.getEmail());
            
         
        }else if (p instanceof PessoaJuridica){
            PessoaJuridica j = (PessoaJuridica)p;
            txtFieldFantasia.setText(j.getNome());
            txtFieldEndereco1.setText(j.getEndereco());
            txtFieldEstadual.setText(j.getInscricaoestadual());
            txtFieldTelefone3.setText(j.getTelefone());
            txtFieldcnpj.setText(j.getCnpj());
            txtFieldEndereco1.setText(j.getEndereco());
            txtFieldEmail1.setText(j.getEmail());
        }
        desabilitar();
        this.setVisible(true);    
    }
      public void desabilitar()
    { 
       
    if (this.jRadioButtonFisica.isSelected()){
        this.jRadioButtonJuridica.setEnabled(false);
        this.txtFieldCPF.setEnabled(true);
        this.txtFieldNome.setEnabled(true);
        this.txtFieldTelefone1.setEnabled(true);
        this.txtFieldTelefone2.setEnabled(true);
        this.txtFieldEmail.setEnabled(true);
        this.txtFieldEndereco.setEnabled(true);
        this.txtFieldrg.setEnabled(true);
        this.txtFieldEmail1.setEnabled(false);
        this.txtFieldTelefone3.setEnabled(false);
        this.txtFieldFantasia.setEnabled(false);
        this.txtFieldEndereco1.setEnabled(false);
        this.txtFieldcnpj.setEnabled(false);
        this.txtFieldEstadual.setEnabled(false); 
        this.btnCadastrar.setEnabled(true);   
       } else {
        this.jRadioButtonFisica.setEnabled(false);
        this.txtFieldCPF.setEnabled(false);
        this.txtFieldNome.setEnabled(false);
        this.txtFieldTelefone1.setEnabled(false);
        this.txtFieldTelefone2.setEnabled(false);
        this.txtFieldEmail.setEnabled(false);
        this.txtFieldEndereco.setEnabled(false);
        this.txtFieldrg.setEnabled(false);
        this.txtFieldEmail1.setEnabled(true);
        this.txtFieldTelefone3.setEnabled(true);
        this.txtFieldFantasia.setEnabled(true);
        this.txtFieldEndereco1.setEnabled(true);
        this.txtFieldcnpj.setEnabled(true);
        this.txtFieldEstadual.setEnabled(true); 
        this.btnCadastrar.setEnabled(true);
       }
        
       
    }
    
    public void desabilitarCampos()
    { 
        this.jRadioButtonFisica.setEnabled(false);
        this.jRadioButtonJuridica.setEnabled(false);
        this.txtFieldCPF.setEnabled(false);
        this.txtFieldNome.setEnabled(false);
        this.txtFieldTelefone1.setEnabled(false);
        this.txtFieldTelefone2.setEnabled(false);
        this.txtFieldTelefone3.setEnabled(false);
        this.txtFieldEmail.setEnabled(false);
        this.txtFieldEmail1.setEnabled(false);
        this.txtFieldrg.setEnabled(false);
        this.txtFieldFantasia.setEnabled(false);
        this.txtFieldEndereco.setEnabled(false);
        this.txtFieldcnpj.setEnabled(false);
        this.txtFieldEstadual.setEnabled(false);
        this.btnCadastrar.setEnabled(false);
        this.btnLimpar.setEnabled(false);
        this.txtFieldEndereco1.setEnabled(false);
        
    }
    
    public void habilitarCampos()
    {
        this.jRadioButtonFisica.setEnabled(true);
        this.jRadioButtonJuridica.setEnabled(true);
        
        this.btnLimpar.setEnabled(true);
    }
    
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

            Pessoa p;
            if (this.jRadioButtonFisica.isSelected()){
                p = new PessoaFisica();
                PessoaFisica fisica = (PessoaFisica) p;
                fisica.setNome(txtFieldNome.getText());
                fisica.setCpf(txtFieldCPF.getText());
                fisica.setEndereco(txtFieldEndereco.getText());
                fisica.setTelefone(txtFieldTelefone1.getText());
                fisica.setCelular(txtFieldTelefone2.getText());
                fisica.setRg(txtFieldrg.getText());
                fisica.setEmail(txtFieldEmail.getText());
                
            } else{
                p = new PessoaJuridica();
                PessoaJuridica juridica = (PessoaJuridica) p;
                juridica.setNome(txtFieldFantasia.getText());
                juridica.setEndereco(txtFieldEndereco1.getText());
                juridica.setTelefone(txtFieldTelefone3.getText());
                juridica.setCnpj(txtFieldcnpj.getText());
                juridica.setInscricaoestadual(txtFieldEstadual.getText());
                juridica.setEmail(txtFieldEmail1.getText());
                
            }
            
            
            this.telaVisualizar.addPessoa(p);
            
         
            JOptionPane.showMessageDialog(this, "Cadastrado com sucesso","Sucesso",JOptionPane.INFORMATION_MESSAGE);
            this.limparCampos();
            
            //não consegui  unir duas arrays para que ambas assumam a mesma posição, conforme queria nos campos Nome/Empresa
            //Consegui fazê-lo mas adicionava mais outra array, fazendo com que repetisse uma em branco toda vez que fosse 
            //efetuado o cadastro
           
    
          
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
            this.setVisible(false);
            this.telaVisualizar.setVisible(true);
            this.habilitarCampos();
            limparCampos();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNomeActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNomeActionPerformed

    private void txtFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCPFActionPerformed

    private void txtFieldTelefone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTelefone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTelefone1ActionPerformed

    private void txtFieldTelefone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTelefone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTelefone2ActionPerformed

    private void txtFieldrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldrgActionPerformed

    private void jRadioButtonFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFisicaActionPerformed

       if(jRadioButtonFisica.isSelected()){
        this.txtFieldCPF.setEnabled(true);
        this.txtFieldNome.setEnabled(true);
        this.txtFieldTelefone1.setEnabled(true);
        this.txtFieldTelefone2.setEnabled(true);
        this.txtFieldEmail.setEnabled(true);
        this.txtFieldEndereco.setEnabled(true);
        this.txtFieldrg.setEnabled(true);
        this.txtFieldEmail1.setEnabled(false);
        this.txtFieldTelefone3.setEnabled(false);
        this.txtFieldFantasia.setEnabled(false);
        this.txtFieldEndereco1.setEnabled(false);
        this.txtFieldcnpj.setEnabled(false);
        this.txtFieldEstadual.setEnabled(false); 
        this.btnCadastrar.setEnabled(true);   
     }
// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFisicaActionPerformed

    private void jRadioButtonJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJuridicaActionPerformed
       if(jRadioButtonJuridica.isSelected()){
        this.txtFieldCPF.setEnabled(false);
        this.txtFieldNome.setEnabled(false);
        this.txtFieldTelefone1.setEnabled(false);
        this.txtFieldTelefone2.setEnabled(false);
        this.txtFieldEmail.setEnabled(false);
        this.txtFieldEndereco.setEnabled(false);
        this.txtFieldrg.setEnabled(false);
        this.txtFieldEmail1.setEnabled(true);
        this.txtFieldTelefone3.setEnabled(true);
        this.txtFieldFantasia.setEnabled(true);
        this.txtFieldEndereco1.setEnabled(true);
        this.txtFieldcnpj.setEnabled(true);
        this.txtFieldEstadual.setEnabled(true); 
        this.btnCadastrar.setEnabled(true);   
       } 
       
       
     
        
// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonJuridicaActionPerformed

    private void txtFieldFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldFantasiaActionPerformed

    private void txtFieldTelefone3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTelefone3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTelefone3ActionPerformed

    private void txtFieldEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEmail1ActionPerformed

    private void txtFieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEnderecoActionPerformed

    private void txtFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEmailActionPerformed

    private void txtFieldcnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldcnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldcnpjActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JRadioButton jRadioButtonFisica;
    private javax.swing.JRadioButton jRadioButtonJuridica;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEndereco1;
    private javax.swing.JLabel lblEstadual;
    private javax.swing.JLabel lblFantasia;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblTelefone1;
    private javax.swing.JLabel lblTelefone2;
    private javax.swing.JLabel lblTelefone3;
    private javax.swing.JFormattedTextField txtFieldCPF;
    private javax.swing.JTextField txtFieldEmail;
    private javax.swing.JTextField txtFieldEmail1;
    private javax.swing.JTextField txtFieldEndereco;
    private javax.swing.JTextField txtFieldEndereco1;
    private javax.swing.JTextField txtFieldEstadual;
    private javax.swing.JTextField txtFieldFantasia;
    private javax.swing.JTextField txtFieldNome;
    private javax.swing.JFormattedTextField txtFieldTelefone1;
    private javax.swing.JFormattedTextField txtFieldTelefone2;
    private javax.swing.JFormattedTextField txtFieldTelefone3;
    private javax.swing.JFormattedTextField txtFieldcnpj;
    private javax.swing.JFormattedTextField txtFieldrg;
    // End of variables declaration//GEN-END:variables
}
