
package interfacegrafica;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VisualizarJFrame extends javax.swing.JFrame {

    //referência para a tela de cadastro
    private CadastroJFrame telaCadastro;
    
    //array para manter as pessoas "salvas"
    private ArrayList<Pessoa> array;
    /**
     * Creates new form VisualizarJFrame
     */
    public VisualizarJFrame() {
        initComponents();
        //inicialização da tela e cadastro
        telaCadastro =  new CadastroJFrame(this);
        
        this.array = new ArrayList<Pessoa>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome/Empresa", "CPF/CNPJ", "RG/Incrição Estadual", "Telefone", "Email", "Endereço"
            }
        ));
        tabela.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Botoes_Site_5742_Knob_Play_Green.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Botoes_Site_5749_Knob_Forward.png"))); // NOI18N
        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Botoes_Site_5750_Knob_Cancel.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setText("Informações Cadastrais:");

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/1481104532_edit-group.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnVisualizar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        
        int linhaSelecionda = tabela.getSelectedRow();
                
        if (linhaSelecionda < 0){
            JOptionPane.showMessageDialog(this, "Selecione uma linha", "Aviso", JOptionPane.WARNING_MESSAGE);
        }else{
            this.telaCadastro.mostrarPessoa(array.get(linhaSelecionda));
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
            //torna a outra tela visível
            this.telaCadastro.setVisible(true);
            
            //torna esta tela invisível
            this.setVisible(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        int selectedIndex = tabela.getSelectedRow();
        
        if (selectedIndex < 0){
            //nenhuma linha selecionada
            JOptionPane.showMessageDialog(this, "Selecione um item","Aviso",JOptionPane.WARNING_MESSAGE);
        }else{
            //um item está selecionado, então remove
            this.removePessoa(selectedIndex);        
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
     int linhaSelecionda = tabela.getSelectedRow();
                
        if (linhaSelecionda < 0){
            JOptionPane.showMessageDialog(this, "Selecione uma linha", "Aviso", JOptionPane.WARNING_MESSAGE);
        }else{
            this.telaCadastro.EditarPessoa(array.get(linhaSelecionda));
            this.setVisible(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    
    //adiciona pessoa a tabela
    public void addPessoa(Pessoa p){
        this.array.add(p);
        this.addPessoaToTable(p);
    }
    
    

    
    
    public void addPessoaToTable(Pessoa p){
        DefaultTableModel model = (DefaultTableModel)tabela.getModel();
        if (p instanceof PessoaFisica){
            PessoaFisica f = (PessoaFisica)p;
            model.addRow(new Object[]{f.getNome(), f.getCpf(), f.getRg(),f.getTelefone(),f.getEndereco(),f.getCelular(),f.getEmail()});    
        }else{
            if (p instanceof PessoaJuridica){
            PessoaJuridica j = (PessoaJuridica)p;
            model.addRow(new Object[]{j.getNome(), j.getCnpj(), j.getInscricaoestadual(),j.getTelefone(), j.getEndereco(),j.getEmail()}); 
            }
        }
        
    }
    
     
    //remove do array
    public void removePessoa(int i){
        array.remove(i);
        removePessoaFromTable(i);
    }
    
    
    //remove da tabela
    public void removePessoaFromTable(int i){
        DefaultTableModel model = (DefaultTableModel)tabela.getModel();
        model.removeRow(i);
    }
    
    
    public void redesenhaTabela(){
        DefaultTableModel model = (DefaultTableModel)tabela.getModel();
        while (model.getRowCount() > 0){
            model.removeRow(0);
        }
        
        for (Pessoa p : array){
            addPessoaToTable(p);
        
        }
  
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
